### ISSUE TITLE
Stl files of the dockingstation

### ISSUE THREAD

**Issue by Ozelot450** [AndreRH/EchoRoot#1]
Hi, I am very interested in this project.
Could you provide the mentioned STL-Files for the dockingstation? I think this would be handy, if you are doing multiple Echos one after another. 
Thank you very much!

**Comment by AndreRH** [comment]
Hi,
Due to agreements with the author of the model, I can only sell it:
https://www.patreon.com/andre_opensource/shop/echoroot-docking-station-3d-model-23089
